// @generated by prost-build from proto/api.proto
//
// To regenerate:
//   1. Temporarily add to Cargo.toml [build-dependencies]: prost-build = "0.13", protox = "0.7"
//   2. Create build.rs: let fds = protox::compile(["proto/api.proto"], ["proto/"]).unwrap();
//      prost_build::Config::new().compile_fds(fds).unwrap();
//   3. cargo build -p rshome-native-api
//   4. cp target/debug/build/rshome-native-api-*/out/esphomelib.rs \
//         crates/rshome-native-api/src/proto_gen/esphomelib.rs
//   5. Remove build.rs and [build-dependencies]
#![allow(clippy::all)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HelloRequest {
    #[prost(string, tag = "1")]
    pub client_info: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub api_version_major: u32,
    #[prost(uint32, tag = "3")]
    pub api_version_minor: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HelloResponse {
    #[prost(uint32, tag = "1")]
    pub api_version_major: u32,
    #[prost(uint32, tag = "2")]
    pub api_version_minor: u32,
    #[prost(string, tag = "3")]
    pub server_info: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DisconnectRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DisconnectResponse {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PingRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PingResponse {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeviceInfoRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceInfoResponse {
    #[prost(bool, tag = "1")]
    pub uses_password: bool,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub mac_address: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub esphome_version: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub compilation_time: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub model: ::prost::alloc::string::String,
    #[prost(bool, tag = "7")]
    pub has_deep_sleep: bool,
    #[prost(string, tag = "8")]
    pub project_name: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub project_version: ::prost::alloc::string::String,
    #[prost(uint32, tag = "10")]
    pub webserver_port: u32,
    #[prost(uint32, tag = "11")]
    pub legacy_bluetooth_proxy_version: u32,
    #[prost(uint32, tag = "12")]
    pub bluetooth_proxy_feature_flags: u32,
    #[prost(string, tag = "13")]
    pub manufacturer: ::prost::alloc::string::String,
    #[prost(string, tag = "14")]
    pub friendly_name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListEntitiesRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListEntitiesDoneResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListEntitiesSensorResponse {
    #[prost(string, tag = "1")]
    pub object_id: ::prost::alloc::string::String,
    #[prost(fixed32, tag = "2")]
    pub key: u32,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub unique_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub icon: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub unit_of_measurement: ::prost::alloc::string::String,
    #[prost(int32, tag = "7")]
    pub accuracy_decimals: i32,
    #[prost(bool, tag = "8")]
    pub force_update: bool,
    #[prost(string, tag = "9")]
    pub device_class: ::prost::alloc::string::String,
    #[prost(int32, tag = "10")]
    pub state_class: i32,
    #[prost(bool, tag = "11")]
    pub disabled_by_default: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListEntitiesBinarySensorResponse {
    #[prost(string, tag = "1")]
    pub object_id: ::prost::alloc::string::String,
    #[prost(fixed32, tag = "2")]
    pub key: u32,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub unique_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub device_class: ::prost::alloc::string::String,
    #[prost(bool, tag = "6")]
    pub is_status_binary_sensor: bool,
    #[prost(bool, tag = "7")]
    pub disabled_by_default: bool,
    #[prost(string, tag = "8")]
    pub icon: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListEntitiesSwitchResponse {
    #[prost(string, tag = "1")]
    pub object_id: ::prost::alloc::string::String,
    #[prost(fixed32, tag = "2")]
    pub key: u32,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub unique_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub icon: ::prost::alloc::string::String,
    #[prost(bool, tag = "6")]
    pub assumed_state: bool,
    #[prost(bool, tag = "7")]
    pub disabled_by_default: bool,
    #[prost(string, tag = "8")]
    pub device_class: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListEntitiesLightResponse {
    #[prost(string, tag = "1")]
    pub object_id: ::prost::alloc::string::String,
    #[prost(fixed32, tag = "2")]
    pub key: u32,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub unique_id: ::prost::alloc::string::String,
    #[prost(int32, repeated, tag = "5")]
    pub supported_color_modes: ::prost::alloc::vec::Vec<i32>,
    #[prost(bool, tag = "6")]
    pub legacy_supports_brightness: bool,
    #[prost(bool, tag = "7")]
    pub legacy_supports_rgb: bool,
    #[prost(bool, tag = "8")]
    pub legacy_supports_white_value: bool,
    #[prost(bool, tag = "9")]
    pub legacy_supports_color_temperature: bool,
    #[prost(float, tag = "10")]
    pub min_mireds: f32,
    #[prost(float, tag = "11")]
    pub max_mireds: f32,
    #[prost(string, repeated, tag = "12")]
    pub effects: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag = "13")]
    pub disabled_by_default: bool,
    #[prost(string, tag = "14")]
    pub icon: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListEntitiesClimateResponse {
    #[prost(string, tag = "1")]
    pub object_id: ::prost::alloc::string::String,
    #[prost(fixed32, tag = "2")]
    pub key: u32,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub unique_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "5")]
    pub supports_current_temperature: bool,
    #[prost(bool, tag = "6")]
    pub supports_two_point_target_temperature: bool,
    #[prost(int32, repeated, tag = "7")]
    pub supported_modes: ::prost::alloc::vec::Vec<i32>,
    #[prost(float, tag = "8")]
    pub visual_min_temperature: f32,
    #[prost(float, tag = "9")]
    pub visual_max_temperature: f32,
    #[prost(float, tag = "10")]
    pub visual_target_temperature_step: f32,
    #[prost(bool, tag = "11")]
    pub legacy_supports_away: bool,
    #[prost(bool, tag = "12")]
    pub supports_action: bool,
    #[prost(int32, repeated, tag = "13")]
    pub supported_fan_modes: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, tag = "14")]
    pub supported_swing_modes: ::prost::alloc::vec::Vec<i32>,
    #[prost(string, repeated, tag = "15")]
    pub supported_custom_fan_modes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int32, repeated, tag = "16")]
    pub supported_presets: ::prost::alloc::vec::Vec<i32>,
    #[prost(string, repeated, tag = "17")]
    pub supported_custom_presets: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag = "18")]
    pub disabled_by_default: bool,
    #[prost(string, tag = "19")]
    pub icon: ::prost::alloc::string::String,
    #[prost(float, tag = "20")]
    pub visual_current_temperature_step: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListEntitiesFanResponse {
    #[prost(string, tag = "1")]
    pub object_id: ::prost::alloc::string::String,
    #[prost(fixed32, tag = "2")]
    pub key: u32,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub unique_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "5")]
    pub supports_oscillation: bool,
    #[prost(bool, tag = "6")]
    pub supports_speed: bool,
    #[prost(bool, tag = "7")]
    pub supports_direction: bool,
    #[prost(int32, tag = "8")]
    pub supported_speed_count: i32,
    #[prost(bool, tag = "9")]
    pub disabled_by_default: bool,
    #[prost(string, tag = "10")]
    pub icon: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListEntitiesCoverResponse {
    #[prost(string, tag = "1")]
    pub object_id: ::prost::alloc::string::String,
    #[prost(fixed32, tag = "2")]
    pub key: u32,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub unique_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub device_class: ::prost::alloc::string::String,
    #[prost(bool, tag = "6")]
    pub assumed_state: bool,
    #[prost(bool, tag = "7")]
    pub supports_position: bool,
    #[prost(bool, tag = "8")]
    pub supports_tilt: bool,
    #[prost(bool, tag = "9")]
    pub disabled_by_default: bool,
    #[prost(string, tag = "10")]
    pub icon: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListEntitiesNumberResponse {
    #[prost(string, tag = "1")]
    pub object_id: ::prost::alloc::string::String,
    #[prost(fixed32, tag = "2")]
    pub key: u32,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub unique_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub icon: ::prost::alloc::string::String,
    #[prost(float, tag = "6")]
    pub min_value: f32,
    #[prost(float, tag = "7")]
    pub max_value: f32,
    #[prost(float, tag = "8")]
    pub step: f32,
    #[prost(bool, tag = "9")]
    pub disabled_by_default: bool,
    #[prost(string, tag = "10")]
    pub unit_of_measurement: ::prost::alloc::string::String,
    #[prost(int32, tag = "11")]
    pub mode: i32,
    #[prost(string, tag = "12")]
    pub device_class: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListEntitiesSelectResponse {
    #[prost(string, tag = "1")]
    pub object_id: ::prost::alloc::string::String,
    #[prost(fixed32, tag = "2")]
    pub key: u32,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub unique_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub icon: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "6")]
    pub options: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag = "7")]
    pub disabled_by_default: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListEntitiesTextSensorResponse {
    #[prost(string, tag = "1")]
    pub object_id: ::prost::alloc::string::String,
    #[prost(fixed32, tag = "2")]
    pub key: u32,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub unique_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub icon: ::prost::alloc::string::String,
    #[prost(bool, tag = "6")]
    pub disabled_by_default: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SubscribeStatesRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SensorStateResponse {
    #[prost(fixed32, tag = "1")]
    pub key: u32,
    #[prost(float, tag = "2")]
    pub state: f32,
    #[prost(bool, tag = "3")]
    pub missing_state: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BinarySensorStateResponse {
    #[prost(fixed32, tag = "1")]
    pub key: u32,
    #[prost(bool, tag = "2")]
    pub state: bool,
    #[prost(bool, tag = "3")]
    pub missing_state: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SwitchStateResponse {
    #[prost(fixed32, tag = "1")]
    pub key: u32,
    #[prost(bool, tag = "2")]
    pub state: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LightStateResponse {
    #[prost(fixed32, tag = "1")]
    pub key: u32,
    #[prost(bool, tag = "2")]
    pub state: bool,
    #[prost(float, tag = "3")]
    pub brightness: f32,
    #[prost(float, tag = "4")]
    pub color_brightness: f32,
    #[prost(float, tag = "5")]
    pub red: f32,
    #[prost(float, tag = "6")]
    pub green: f32,
    #[prost(float, tag = "7")]
    pub blue: f32,
    #[prost(float, tag = "8")]
    pub white: f32,
    #[prost(float, tag = "9")]
    pub color_temperature: f32,
    #[prost(float, tag = "10")]
    pub cold_white: f32,
    #[prost(float, tag = "11")]
    pub warm_white: f32,
    #[prost(string, tag = "12")]
    pub effect: ::prost::alloc::string::String,
    #[prost(int32, tag = "13")]
    pub color_mode: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClimateStateResponse {
    #[prost(fixed32, tag = "1")]
    pub key: u32,
    #[prost(int32, tag = "2")]
    pub mode: i32,
    #[prost(float, tag = "3")]
    pub current_temperature: f32,
    #[prost(float, tag = "4")]
    pub target_temperature: f32,
    #[prost(bool, tag = "5")]
    pub unused_legacy_away: bool,
    #[prost(int32, tag = "6")]
    pub action: i32,
    #[prost(int32, tag = "7")]
    pub fan_mode: i32,
    #[prost(int32, tag = "8")]
    pub swing_mode: i32,
    #[prost(string, tag = "9")]
    pub custom_fan_mode: ::prost::alloc::string::String,
    #[prost(int32, tag = "10")]
    pub preset: i32,
    #[prost(string, tag = "11")]
    pub custom_preset: ::prost::alloc::string::String,
    #[prost(float, tag = "12")]
    pub target_temperature_low: f32,
    #[prost(float, tag = "13")]
    pub target_temperature_high: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct FanStateResponse {
    #[prost(fixed32, tag = "1")]
    pub key: u32,
    #[prost(bool, tag = "2")]
    pub state: bool,
    #[prost(bool, tag = "3")]
    pub oscillating: bool,
    #[prost(int32, tag = "4")]
    pub speed_level: i32,
    #[prost(int32, tag = "5")]
    pub direction: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CoverStateResponse {
    #[prost(fixed32, tag = "1")]
    pub key: u32,
    #[prost(float, tag = "2")]
    pub legacy_state: f32,
    #[prost(float, tag = "3")]
    pub position: f32,
    #[prost(float, tag = "4")]
    pub tilt: f32,
    #[prost(int32, tag = "5")]
    pub current_operation: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct NumberStateResponse {
    #[prost(fixed32, tag = "1")]
    pub key: u32,
    #[prost(float, tag = "2")]
    pub state: f32,
    #[prost(bool, tag = "3")]
    pub missing_state: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SelectStateResponse {
    #[prost(fixed32, tag = "1")]
    pub key: u32,
    #[prost(string, tag = "2")]
    pub state: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub missing_state: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TextSensorStateResponse {
    #[prost(fixed32, tag = "1")]
    pub key: u32,
    #[prost(string, tag = "2")]
    pub state: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub missing_state: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SwitchCommandRequest {
    #[prost(fixed32, tag = "1")]
    pub key: u32,
    #[prost(bool, tag = "2")]
    pub state: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LightCommandRequest {
    #[prost(fixed32, tag = "1")]
    pub key: u32,
    #[prost(bool, tag = "2")]
    pub has_state: bool,
    #[prost(bool, tag = "3")]
    pub state: bool,
    #[prost(bool, tag = "4")]
    pub has_brightness: bool,
    #[prost(float, tag = "5")]
    pub brightness: f32,
    #[prost(bool, tag = "6")]
    pub has_color_mode: bool,
    #[prost(int32, tag = "7")]
    pub color_mode: i32,
    #[prost(bool, tag = "8")]
    pub has_color_brightness: bool,
    #[prost(float, tag = "9")]
    pub color_brightness: f32,
    #[prost(bool, tag = "10")]
    pub has_rgb: bool,
    #[prost(float, tag = "11")]
    pub red: f32,
    #[prost(float, tag = "12")]
    pub green: f32,
    #[prost(float, tag = "13")]
    pub blue: f32,
    #[prost(bool, tag = "14")]
    pub has_white: bool,
    #[prost(float, tag = "15")]
    pub white: f32,
    #[prost(bool, tag = "16")]
    pub has_color_temperature: bool,
    #[prost(float, tag = "17")]
    pub color_temperature: f32,
    #[prost(bool, tag = "18")]
    pub has_cold_white: bool,
    #[prost(float, tag = "19")]
    pub cold_white: f32,
    #[prost(bool, tag = "20")]
    pub has_warm_white: bool,
    #[prost(float, tag = "21")]
    pub warm_white: f32,
    #[prost(bool, tag = "22")]
    pub has_transition_length: bool,
    #[prost(uint32, tag = "23")]
    pub transition_length: u32,
    #[prost(bool, tag = "24")]
    pub has_flash_length: bool,
    #[prost(uint32, tag = "25")]
    pub flash_length: u32,
    #[prost(bool, tag = "26")]
    pub has_effect: bool,
    #[prost(string, tag = "27")]
    pub effect: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClimateCommandRequest {
    #[prost(fixed32, tag = "1")]
    pub key: u32,
    #[prost(bool, tag = "2")]
    pub has_mode: bool,
    #[prost(int32, tag = "3")]
    pub mode: i32,
    #[prost(bool, tag = "4")]
    pub has_target_temperature: bool,
    #[prost(float, tag = "5")]
    pub target_temperature: f32,
    #[prost(bool, tag = "6")]
    pub has_target_temperature_low: bool,
    #[prost(float, tag = "7")]
    pub target_temperature_low: f32,
    #[prost(bool, tag = "8")]
    pub has_target_temperature_high: bool,
    #[prost(float, tag = "9")]
    pub target_temperature_high: f32,
    #[prost(bool, tag = "10")]
    pub unused_has_legacy_away: bool,
    #[prost(bool, tag = "11")]
    pub unused_legacy_away: bool,
    #[prost(bool, tag = "12")]
    pub has_fan_mode: bool,
    #[prost(int32, tag = "13")]
    pub fan_mode: i32,
    #[prost(bool, tag = "14")]
    pub has_swing_mode: bool,
    #[prost(int32, tag = "15")]
    pub swing_mode: i32,
    #[prost(bool, tag = "16")]
    pub has_custom_fan_mode: bool,
    #[prost(string, tag = "17")]
    pub custom_fan_mode: ::prost::alloc::string::String,
    #[prost(bool, tag = "18")]
    pub has_preset: bool,
    #[prost(int32, tag = "19")]
    pub preset: i32,
    #[prost(bool, tag = "20")]
    pub has_custom_preset: bool,
    #[prost(string, tag = "21")]
    pub custom_preset: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct FanCommandRequest {
    #[prost(fixed32, tag = "1")]
    pub key: u32,
    #[prost(bool, tag = "2")]
    pub has_state: bool,
    #[prost(bool, tag = "3")]
    pub state: bool,
    #[prost(bool, tag = "4")]
    pub has_speed: bool,
    #[prost(int32, tag = "5")]
    pub speed: i32,
    #[prost(bool, tag = "6")]
    pub has_oscillating: bool,
    #[prost(bool, tag = "7")]
    pub oscillating: bool,
    #[prost(bool, tag = "8")]
    pub has_direction: bool,
    #[prost(int32, tag = "9")]
    pub direction: i32,
    #[prost(bool, tag = "10")]
    pub has_speed_level: bool,
    #[prost(int32, tag = "11")]
    pub speed_level: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CoverCommandRequest {
    #[prost(fixed32, tag = "1")]
    pub key: u32,
    #[prost(bool, tag = "2")]
    pub has_legacy_command: bool,
    #[prost(int32, tag = "3")]
    pub legacy_command: i32,
    #[prost(bool, tag = "4")]
    pub has_position: bool,
    #[prost(float, tag = "5")]
    pub position: f32,
    #[prost(bool, tag = "6")]
    pub has_tilt: bool,
    #[prost(float, tag = "7")]
    pub tilt: f32,
    #[prost(bool, tag = "8")]
    pub stop: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct NumberCommandRequest {
    #[prost(fixed32, tag = "1")]
    pub key: u32,
    #[prost(float, tag = "2")]
    pub state: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SelectCommandRequest {
    #[prost(fixed32, tag = "1")]
    pub key: u32,
    #[prost(string, tag = "2")]
    pub state: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ButtonCommandRequest {
    #[prost(fixed32, tag = "1")]
    pub key: u32,
}
