//! CMake file generation for ESP-IDF projects.
//!
//! These functions use direct string formatting (no Tera) so they can return
//! `String` without propagating template errors.

/// Generate the root `CMakeLists.txt` for an ESP-IDF project.
pub fn generate_root_cmake(project_name: &str) -> String {
    format!(
        "cmake_minimum_required(VERSION 3.16)\n\
         \n\
         include($ENV{{IDF_PATH}}/tools/cmake/project.cmake)\n\
         \n\
         project({project_name})\n"
    )
}

/// Generate an `idf_component_register(...)` CMakeLists.txt for a component.
///
/// - `sources` — source files relative to the component directory (e.g. `["src/foo.c"]`)
/// - `requires` — public component dependencies (available to dependents)
/// - `priv_requires` — private component dependencies (not propagated)
pub fn generate_component_cmake(
    sources: &[&str],
    requires: &[&str],
    priv_requires: &[&str],
) -> String {
    let srcs = if sources.is_empty() {
        String::new()
    } else {
        let items: Vec<String> = sources.iter().map(|s| format!("    \"{s}\"")).collect();
        format!("\n    SRCS\n{}", items.join("\n"))
    };

    let reqs = if requires.is_empty() {
        String::new()
    } else {
        let items: Vec<String> = requires.iter().map(|r| format!("    \"{r}\"")).collect();
        format!("\n    REQUIRES\n{}", items.join("\n"))
    };

    let priv_reqs = if priv_requires.is_empty() {
        String::new()
    } else {
        let items: Vec<String> = priv_requires
            .iter()
            .map(|r| format!("    \"{r}\""))
            .collect();
        format!("\n    PRIV_REQUIRES\n{}", items.join("\n"))
    };

    format!(
        "idf_component_register(\n\
         {srcs}\
         \n    INCLUDE_DIRS\n    \"include\"\
         {reqs}\
         {priv_reqs}\n)\n"
    )
}

/// Generate the `#pragma once` + `#define` header for `USE_*` feature flags
/// and (when present) WiFi provisioning-mode constants.
///
/// `active_flags` is the `ValidatedConfig::active_flags` slice (already sorted
/// USE_* names).  `wifi_config` is the raw JSON config for the `wifi` component
/// (if one exists); it drives the `RSHOME_WIFI_PROV_*` section.
/// The output is suitable for inclusion as `rshome_defines.h`.
pub fn generate_defines_header(
    active_flags: &[String],
    wifi_config: Option<&serde_json::Value>,
) -> String {
    let mut lines: Vec<String> = active_flags
        .iter()
        .map(|f| format!("#define {f}"))
        .collect();

    if let Some(wifi_cfg) = wifi_config {
        lines.push("#define RSHOME_WIFI_PROV_NVS         0".to_string());
        lines.push("#define RSHOME_WIFI_PROV_BUILD_INPUT 1".to_string());

        let mode_num = if wifi_cfg
            .get("provisioning_mode")
            .and_then(|value| value.as_str())
            == Some("build_input")
        {
            1
        } else {
            0
        };
        lines.push(format!("#define RSHOME_WIFI_PROV_MODE        {mode_num}"));

        if mode_num == 1 {
            let ssid = wifi_cfg.get("ssid").and_then(|value| value.as_str());
            let password = wifi_cfg.get("password").and_then(|value| value.as_str());
            let valid = ssid.is_some_and(|value| !value.is_empty())
                && password.is_some_and(|value| !value.is_empty());
            lines.push(format!(
                "#define RSHOME_WIFI_BUILD_INPUT_VALID {}",
                u8::from(valid)
            ));
            if let (Some(ssid), Some(password)) = (ssid, password) {
                if valid {
                    lines.push(format!("#define RSHOME_WIFI_BUILD_SSID \"{ssid}\""));
                    lines.push(format!("#define RSHOME_WIFI_BUILD_PASSWORD \"{password}\""));
                }
            }
        }
    }

    lines.sort();
    format!(
        "#pragma once\n\
         // Auto-generated by rshome-codegen. Do not edit.\n\
         \n\
         {}",
        lines.join("\n")
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn root_cmake_contains_project_name() {
        let cmake = generate_root_cmake("my_firmware");
        assert!(cmake.contains("project(my_firmware)"));
    }

    #[test]
    fn root_cmake_has_cmake_minimum_required() {
        let cmake = generate_root_cmake("test");
        assert!(cmake.contains("cmake_minimum_required(VERSION 3.16)"));
    }

    #[test]
    fn root_cmake_includes_idf_cmake() {
        let cmake = generate_root_cmake("test");
        assert!(cmake.contains("include($ENV{IDF_PATH}/tools/cmake/project.cmake)"));
    }

    #[test]
    fn component_cmake_contains_sources() {
        let cmake = generate_component_cmake(&["src/app_main.c"], &["rshome_core"], &[]);
        assert!(cmake.contains("\"src/app_main.c\""));
    }

    #[test]
    fn component_cmake_contains_requires() {
        let cmake = generate_component_cmake(&[], &["rshome_core", "hal"], &[]);
        assert!(cmake.contains("\"rshome_core\""));
        assert!(cmake.contains("\"hal\""));
    }

    #[test]
    fn component_cmake_contains_priv_requires() {
        let cmake = generate_component_cmake(&[], &[], &["freertos"]);
        assert!(cmake.contains("\"freertos\""));
        assert!(cmake.contains("PRIV_REQUIRES"));
    }

    #[test]
    fn component_cmake_no_priv_requires() {
        let cmake = generate_component_cmake(&["src/foo.c"], &["rshome_core"], &[]);
        assert!(!cmake.contains("PRIV_REQUIRES"));
    }

    #[test]
    fn component_cmake_includes_dir() {
        let cmake = generate_component_cmake(&[], &[], &[]);
        assert!(cmake.contains("INCLUDE_DIRS"));
        assert!(cmake.contains("\"include\""));
    }

    #[test]
    fn defines_header_has_pragma_once() {
        let flags = vec!["USE_WIFI".to_string(), "USE_SENSOR".to_string()];
        let header = generate_defines_header(&flags, None);
        assert!(header.starts_with("#pragma once"));
    }

    #[test]
    fn defines_header_contains_flags() {
        let flags = vec!["USE_WIFI".to_string(), "USE_LOGGER".to_string()];
        let header = generate_defines_header(&flags, None);
        assert!(header.contains("#define USE_WIFI"));
        assert!(header.contains("#define USE_LOGGER"));
    }

    #[test]
    fn defines_header_sorted() {
        let flags = vec![
            "USE_WIFI".to_string(),
            "USE_API".to_string(),
            "USE_SENSOR".to_string(),
        ];
        let header = generate_defines_header(&flags, None);
        let define_lines: Vec<&str> = header
            .lines()
            .filter(|l| l.starts_with("#define"))
            .collect();
        let mut sorted = define_lines.clone();
        sorted.sort();
        assert_eq!(define_lines, sorted, "defines not sorted");
    }

    #[test]
    fn defines_header_empty_flags() {
        let flags: Vec<String> = vec![];
        let header = generate_defines_header(&flags, None);
        assert!(header.starts_with("#pragma once"));
        let define_count = header.lines().filter(|l| l.starts_with("#define")).count();
        assert_eq!(define_count, 0);
    }

    #[test]
    fn defines_header_wifi_defaults_to_nvs_without_credentials() {
        use serde_json::json;
        let flags = vec!["USE_WIFI".to_string()];
        let wifi_cfg = json!({"provisioning_mode": "nvs"});
        let header = generate_defines_header(&flags, Some(&wifi_cfg));
        assert!(header.contains("#define RSHOME_WIFI_PROV_MODE        0"));
        assert!(header.contains("#define RSHOME_WIFI_PROV_NVS         0"));
        assert!(!header.contains("RSHOME_WIFI_BUILD_SSID"));
        assert!(!header.contains("RSHOME_WIFI_BUILD_PASSWORD"));
    }

    #[test]
    fn defines_header_wifi_build_input_emits_only_explicit_values() {
        use serde_json::json;
        let flags = vec!["USE_WIFI".to_string()];
        let wifi_cfg = json!({
            "provisioning_mode": "build_input",
            "ssid": "unit-net",
            "password": "unit-password"
        });
        let header = generate_defines_header(&flags, Some(&wifi_cfg));
        assert!(header.contains("#define RSHOME_WIFI_PROV_MODE        1"));
        assert!(header.contains("#define RSHOME_WIFI_BUILD_INPUT_VALID 1"));
        assert!(header.contains("#define RSHOME_WIFI_BUILD_SSID \"unit-net\""));
        assert!(header.contains("#define RSHOME_WIFI_BUILD_PASSWORD \"unit-password\""));
    }

    #[test]
    fn defines_header_wifi_incomplete_build_input_omits_credentials() {
        use serde_json::json;
        let flags = vec!["USE_WIFI".to_string()];
        let wifi_cfg = json!({"provisioning_mode": "build_input", "ssid": "unit-net"});
        let header = generate_defines_header(&flags, Some(&wifi_cfg));
        assert!(header.contains("#define RSHOME_WIFI_BUILD_INPUT_VALID 0"));
        assert!(!header.contains("RSHOME_WIFI_BUILD_SSID"));
        assert!(!header.contains("RSHOME_WIFI_BUILD_PASSWORD"));
    }

    #[test]
    fn defines_header_wifi_prov_mode_defines_are_sorted() {
        use serde_json::json;
        let flags = vec!["USE_WIFI".to_string()];
        let wifi_cfg = json!({"provisioning_mode": "nvs"});
        let header = generate_defines_header(&flags, Some(&wifi_cfg));
        let define_lines: Vec<&str> = header
            .lines()
            .filter(|l| l.starts_with("#define"))
            .collect();
        let mut sorted = define_lines.clone();
        sorted.sort();
        assert_eq!(define_lines, sorted, "defines not sorted");
    }
}
