use rshome_config::ValidatedConfig;
use rshome_schema::ChipTarget;

pub fn generate_sdkconfig(config: &ValidatedConfig) -> String {
    let target = match config.esphome.chip_target {
        ChipTarget::Esp32 => "esp32",
        ChipTarget::Esp32S2 => "esp32s2",
        ChipTarget::Esp32S3 => "esp32s3",
        ChipTarget::Esp32C2 => "esp32c2",
        ChipTarget::Esp32C3 => "esp32c3",
        ChipTarget::Esp32C5 => "esp32c5",
        ChipTarget::Esp32C6 => "esp32c6",
        ChipTarget::Esp32C61 => "esp32c61",
        ChipTarget::Esp32H2 => "esp32h2",
        ChipTarget::Esp32P4 => "esp32p4",
        _ => "esp32",
    };
    let has_flag = |flag: &str| config.active_flags.iter().any(|active| active == flag);
    let mut lines = vec![
        "# Generated by rshome-codegen.".to_owned(),
        format!("CONFIG_IDF_TARGET=\"{target}\""),
        "CONFIG_ESPTOOLPY_FLASHSIZE_16MB=y".to_owned(),
        "CONFIG_PARTITION_TABLE_CUSTOM=y".to_owned(),
        "CONFIG_PARTITION_TABLE_CUSTOM_FILENAME=\"partitions.csv\"".to_owned(),
        "CONFIG_LOG_DEFAULT_LEVEL_INFO=y".to_owned(),
    ];
    if has_flag("USE_WIFI") {
        lines.push("CONFIG_ESP_WIFI_ENABLED=y".to_owned());
        lines.push("CONFIG_LWIP_IPV4=y".to_owned());
    }
    if has_flag("USE_BLE") {
        lines.push("CONFIG_BT_ENABLED=y".to_owned());
        lines.push("CONFIG_BT_NIMBLE_ENABLED=y".to_owned());
    }
    if has_flag("USE_API") {
        lines.push("CONFIG_MBEDTLS_TLS_SERVER=y".to_owned());
        lines.push("CONFIG_MBEDTLS_TLS_CLIENT_ONLY=n".to_owned());
    }
    lines.join("\n")
}
